#!/usr/bin/env python
'''
pushci - Push your CI metrics to librato, statsd, ...

Usage:
    pushci [options]
    pushci (junit|coverage) <path> [options] 
    pushci -h | --help

Options:
    -c <ci>, --ci <ci>
    -b <backend>, --backend <backend>
    -s <suite_name>, --suite-name <suite_name>
    -f <config_file>, --config-file <config_file> 
    -d, --debug
'''
from docopt import docopt
import cipush.push

if __name__ == '__main__':
    args = docopt(__doc__)
    cipush.push.push(args)    
